a=input("enter a")
b=input("enter b")
c=int(a)+int(b)
print("addition of ",a,"and",b,"is",c)
d=int(a)-int(b)
print("subtraction of ",a,"and",b,"is",d)
e=int(a)/int(b)
print("division of ",a,"and",b,"is",e)
f=int(a)*int(b)
print("multiplication of ",a,"and",b,"is",f)